Handle errors from MEA in algo instance
LykkeCity/Lykke.AlgoStore.CSharp.AlgoTemplate pull request #106
Opened 2018-06-19 16:36 UTC by filip-prime

2018-06-20 07:47 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.CSharp.AlgoTemplate.Core/Lykke.AlgoStore.CSharp.AlgoTemplate.Core.csproj
> +    <ProjectReference Include="..\Lykke.AlgoStore.CSharp.AlgoTemplate.Abstractions\Lykke.AlgoStore.CSharp.AlgoTemplate.Abstractions.csproj" />
we should update first the Abstractions in order to use the NuGet package instead of the project reference...

2018-06-20 11:25 UTC, mjoksa approved these changes

2018-06-21 07:27 UTC, ghost requested changes

2018-06-21 07:27 UTC, ghost commented on src/Lykke.AlgoStore.CSharp.AlgoTemplate.Core/Constants.cs
> +        public const int ServiceCallTimoutSeconds = 10;
Timout -> Timeout

2018-06-21 07:27 UTC, ghost commented on src/Lykke.AlgoStore.CSharp.AlgoTemplate.Abstractions/Core/ResponseModels/TradeResponse.cs
> +    public class TradeResponse : ServiceResponse<double, TradeErrorCode>
If the CreateOk and CreateFail should be the only ways to create a TradeResponse, you should add a private constructor

2018-06-21 07:27 UTC, ghost commented on src/Lykke.AlgoStore.CSharp.AlgoTemplate.Services/Extensions/TaskExtensions.cs
> +            return await task.ContinueWith(t => t.GetAwaiter().GetResult(), token);
This will not work the way it is intended, ContinueWith tasks are only fired when the previous task completes, so awaiting it here will just return instantly, and if the original task blocks, ContinueWith will never be called. 
An alternative is to use Task.WhenAny with a Task.Delay, but the best solution would be to modify the logic in the MEA client itself

2018-06-21 14:02 UTC, ghost approved these changes

2018-06-21 14:24 UTC, iliyan-ivanov-prime approved these changes

2018-06-21 14:42 UTC, merged