Feature al 261 implement algo instance metadata repository
LykkeCity/Lykke.AlgoStore.CSharp.AlgoTemplate pull request #18
Opened 2018-02-23 12:53 UTC by iliyan-ivanov-prime

2018-02-23 14:29 UTC, dafinkagerdjikova requested changes

2018-02-23 14:29 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.CSharp.AlgoTemplate.Services/Services/MatchingEngineAdapter.cs
> +        //public async Task<ResponseModel<Guid>> PlaceLimitOrderAsync(string clientId, string assetPairId, Core.Domain.OrderAction orderAction, double volume,
If these comments are not needed...why we don't delete them

2018-02-26 09:19 UTC, dafinkagerdjikova approved these changes

2018-02-26 09:59 UTC, mjoksa approved these changes

2018-03-02 07:47 UTC, mjoksa approved these changes

2018-03-02 07:58 UTC, merged